"""
Django settings for educa project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from django.urls import reverse_lazy
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--0pkbs_tt6!+4@vytt+qz87e_2m)if!-0om870wl5tf6)sx=r='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'chat.apps.ChatConfig',
    'rest_framework',   # NEW: Django REST framework application
    'redisboard',   # Adds Redis metrics to the Django admin site
    'debug_toolbar',   # NEW: cache/SQL inspection panels
    'embed_video',
    # New app: handles student registration and enrollment
    'students.apps.StudentsConfig',
    'courses.apps.CoursesConfig',  # Our custom app
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # PER-SITE CACHE: stores every GET response (temporary experiment)
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    # PER-SITE CACHE: serves cached responses (temporary experiment)
    'django.middleware.cache.FetchFromCacheMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Per-site cache configuration
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 60 * 15   # 15 minutes
CACHE_MIDDLEWARE_KEY_PREFIX = 'educa'  # avoid key collisions across projects

ROOT_URLCONF = 'educa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'educa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# Media Files Configuration
# ==========================================
# Base URL to serve user-uploaded media files (images, videos, etc.)
MEDIA_URL = 'media/'

# Local filesystem path where media files will be physically stored
MEDIA_ROOT = BASE_DIR / 'media'

# reverse_lazy resolves the URL lazily at first use, not at import time

# Where to send users after a successful login when no ?next= is present
# (this fixes the old /accounts/profile/ 404!)
LOGIN_REDIRECT_URL = reverse_lazy('student_course_list')

# Low-level cache configuration — Windows-friendly, no Docker needed.
# LocMemCache keeps cached data in the process memory (like Memcached,
# but local). In Module 6 we will switch to Redis via Docker Compose.
CACHES = {
    'default': {
        # 'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        #  'LOCATION': 'educa-cache',  # Unique name for this cache instance

        # Redis backend: memory-based, shared, production-grade
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379',
    }
}

INTERNAL_IPS = [
    '127.0.0.1',
    '::1',
]

# Global DRF configuration
REST_FRAMEWORK = {
    # Default rule: anonymous users get READ-ONLY access;
    # write operations require the matching Django model permissions
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}

# Tells Channels where to find the root ASGI routing configuration
ASGI_APPLICATION = 'educa.asgi.application'
